import React from 'react'

export const PositionTableConfig = {
  columns: [
    { label: 'Code', key: 'pos_code', className: 'min-w-[120px] border p-4' },
    { 
      label: 'Name', 
      key: 'pos_name', 
      className: 'min-w-[200px] border p-4',
      format: (value: string, row: any) => {
        const name = value || '-'
        const isAutoGenerated = row?.creation_type === 'auto'
        if (isAutoGenerated) {
          // Return JSX as a React element
          return (
            <span className="flex items-center gap-2">
              <span>{name}</span>
              <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200" title="Auto-generated position">
                Auto
              </span>
            </span>
          )
        }
        return name
      },
    },
    { 
      label: 'Faculty', 
      key: 'faculty.name', 
      className: 'min-w-[200px] border p-4',
      format: (value: string, row: any) => row?.faculty?.name || '-',
    },
    { 
      label: 'Department', 
      key: 'department.name', 
      className: 'min-w-[200px] border p-4',
      format: (value: string, row: any) => row?.department?.name || '-',
    },
    { 
      label: 'Position Category', 
      key: 'position_category', 
      className: 'min-w-[200px] border p-4',
      format: (value: string) => {
        if (!value) return '-'
        const categoryLabels: Record<string, string> = {
          'executive': 'Executive Positions',
          'academic_teaching': 'Academic (Teaching)',
          'academic_support': 'Academic Support',
          'administrative_non_teaching': 'Administrative (Non-Teaching)',
          'technical_skilled': 'Technical / Skilled',
          'support_utility': 'Support / Utility',
          'specialized_compliance': 'Specialized / Compliance',
        }
        return categoryLabels[value] || value.split('_').map((word: string) => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')
      },
    },
    { label: 'Hierarchy Level', key: 'hierarchy_level', className: 'min-w-[140px] border p-4 text-center' },
    {
      label: 'Capacity',
      key: 'capacity',
      className: 'min-w-[120px] border p-4 text-center',
      format: (value: number | null) => value !== null && value !== undefined ? String(value) : 'Unlimited',
    },
    {
      label: 'Description',
      key: 'description',
      className: 'border p-4 whitespace-pre-wrap break-words',
      format: (value: string) => value || '-',
    },
    { label: 'Actions', key: 'actions', isAction: true, className: 'border p-4' },
  ],
  actions: [
    { label: 'View', icon: 'Eye', className: 'cursor-pointer rounded-lg bg-sky-600 p-2 text-white hover:opacity-90', permission: 'view-position' },
    { label: 'Edit', icon: 'Pencil', className: 'ms-2 cursor-pointer rounded-lg bg-blue-600 p-2 text-white hover:opacity-90', permission: 'edit-position' },
    { label: 'Delete', icon: 'Trash2', route: 'positions.destroy', className: 'ms-2 cursor-pointer rounded-lg bg-red-600 p-2 text-white hover:opacity-90', permission: 'delete-position' },
  ],
}

