import { CirclePlus } from 'lucide-react'

export const POSITION_CATEGORY_OPTIONS = [
  { label: 'Executive Positions', value: 'executive', key: 'executive' },
  { label: 'Academic (Teaching)', value: 'academic_teaching', key: 'academic_teaching' },
  { label: 'Academic Support', value: 'academic_support', key: 'academic_support' },
  { label: 'Administrative (Non-Teaching)', value: 'administrative_non_teaching', key: 'administrative_non_teaching' },
  { label: 'Technical / Skilled', value: 'technical_skilled', key: 'technical_skilled' },
  { label: 'Support / Utility', value: 'support_utility', key: 'support_utility' },
  { label: 'Specialized / Compliance', value: 'specialized_compliance', key: 'specialized_compliance' },
]

export const POSITION_CATEGORY_DESCRIPTIONS: Record<string, string> = {
  executive: 'Office only (administrative department)',
  academic_teaching: 'Faculty + Department required',
  academic_support: 'Allow either (1) Faculty+Department OR (2) Faculty only OR (3) Office only',
  administrative_non_teaching: 'Office only (administrative department)',
  technical_skilled: 'Allow either (1) Faculty+Department OR (2) Office only',
  support_utility: 'Office only (administrative department)',
  specialized_compliance: 'Office only (administrative department)',
}

export const PositionModalFormConfig = {
  moduleTitle: 'Manage Positions',
  title: 'Create Position',
  description: 'Provide the position details below.',
  addButton: {
    id: 'add-position',
    label: 'Add Position',
    className: 'bg-primary text-primary-foreground rounded-lg px-4 py-2 hover:bg-primary/90 cursor-pointer',
    icon: CirclePlus,
    type: 'button',
    variant: 'default',
    permission: 'create-position',
  },
  fields: [
    {
      id: 'pos-code',
      key: 'pos_code',
      name: 'pos_code',
      label: 'Position Code',
      type: 'text',
      placeholder: 'e.g. PROF',
      autocomplete: 'off',
      tabIndex: 1,
    },
    {
      id: 'pos-name',
      key: 'pos_name',
      name: 'pos_name',
      label: 'Position Name',
      type: 'text',
      placeholder: 'Enter position name',
      autocomplete: 'off',
      tabIndex: 2,
    },
    {
      id: 'position-category',
      key: 'position_category',
      name: 'position_category',
      label: 'Position Category',
      type: 'single-select',
      placeholder: 'Select Position Category',
      options: POSITION_CATEGORY_OPTIONS,
      tabIndex: 3,
      required: true,
    },
    {
      id: 'faculty-id',
      key: 'faculty_id',
      name: 'faculty_id',
      label: 'Faculty',
      type: 'single-select',
      placeholder: 'Select Faculty',
      tabIndex: 4,
    },
    {
      id: 'department-id',
      key: 'department_id',
      name: 'department_id',
      label: 'Department / Office',
      type: 'single-select',
      placeholder: 'Select Department or Office',
      tabIndex: 5,
    },
    {
      id: 'hierarchy-level',
      key: 'hierarchy_level',
      name: 'hierarchy_level',
      label: 'Hierarchy Level',
      type: 'number',
      placeholder: 'e.g. 5',
      min: 1,
      tabIndex: 6,
    },
    {
      id: 'capacity',
      key: 'capacity',
      name: 'capacity',
      label: 'Capacity (Leave empty for unlimited)',
      type: 'number',
      placeholder: 'e.g. 1 (leave empty for no limit)',
      min: 1,
      tabIndex: 7,
    },
    {
      id: 'pos-description',
      key: 'description',
      name: 'description',
      label: 'Description',
      type: 'textarea',
      placeholder: 'Optional description',
      tabIndex: 8,
      rows: 3,
      className: 'rounded border p-2 w-full',
    },
  ],
  buttons: [
    {
      key: 'cancel',
      type: 'button',
      label: 'Cancel',
      variant: 'ghost',
      className: 'cursor-pointer',
    },
    {
      key: 'submit',
      type: 'submit',
      label: 'Save Position',
      variant: 'default',
      className: 'cursor-pointer',
    },
  ],
}

